FROM elixir:1.11-alpine as build

# install build dependencies
RUN apk add --update git build-base nodejs npm yarn

# Install Hex + Rebar
RUN mix do local.hex --force, local.rebar --force

# set build ENV
ENV MIX_ENV=dev

WORKDIR /app

# Install mix dependencies
COPY mix.* ./
RUN mix deps.get
RUN mix deps.compile

# Install JS dependencies
COPY ./assets/package*.json ./assets/
RUN yarn --cwd ./assets

CMD mix phx.server
